config/routes.rb
SampleApp::Application.routes.draw do
  get "rides/new"
  resources :users
  resources :rides do
    collection do
      get 'for/:auto', action: 'for'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match 'admin', to: 'static_pages#admin', via: 'get'
  match 'passengers', to: 'static_pages#passengers', via: 'get'
  match 'profile', to: 'static_pages#profile', via: 'get'
  match 'new', to: 'static_pages#new', via: 'get'
  match 'enter', to: 'static_pages#enter', via: 'get'
  match 'help', to: 'static_pages#help', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides, dependent: :destroy
	before_save { self.phone = phone }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	validates :lastname, presence: true, length: { maximum: 50 }
	VALID_PHONE_REGEX = /\A[\d|\+|\(]+[\)|\d|\s|-]*[\d]\z/
	validates :phone, presence: true, format: { with: VALID_PHONE_REGEX }, uniqueness: true
	validates :settlement, presence: true
	has_secure_password
	validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def new
  end

  def for
    render partial: valid_autos.detect{|p| p == params[:auto] }
  end

  private

  def valid_autos
    ['gazel', 'hundai', 'mercedes']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(phone: params[:session][:phone].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_url#user
    else
      flash.now[:error] = 'Неверная комбинация телефон/пароль'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def admin
  end

  def passengers
  end

  def profile
  end

  def new
  end

  def enter
  end

  def help
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Добро пожаловать!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Профиль обновлён"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь удалён."
    redirect_to users_url
  end


  private

  def user_params
  	params.require(:user).permit(:name, :lastname, :phone, :settlement, :password, :password_confirmation)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Пожалуйста, войдите."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Бронь"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
  	user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Бронирование билетов", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <!--<li><%= link_to "Главная", root_path %></li>-->
          <!--<li><%= link_to "Help", help_path %></li>-->
          <% if signed_in? %>
            <li><%= link_to "Пассажиры", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Аккаунт <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Войти", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/rides/_gazel.html.erb
Газель

<div class="table table-hover table-bordered">
<table>
  <thead>
    <tr>
      <th>Место</th>
      <th>Пассажир</th>
      <th>Откуда</th>
      <th>Дата бронирования</th>
    </tr>   
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
    </tr>
    <tr>
      <td>1</td>
      <td>1</td>
      <td>1</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

app/views/rides/_hyundai.html.erb
<% provide(:transport_name, 'автобус "Hyundai"') %>
<div class="table table-hover table-bordered">
<table>
  <thead>
    <tr>
      <th>Место</th>
      <th>Пассажир</th>
      <th>Откуда</th>
      <th>Дата бронирования</th>
    </tr>   
  </thead>
  <tbody>
    <tr>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>

app/views/rides/_mercedes.html.erb
<% provide(:transport_name, 'микроавтобус "Mercedes"') %>
<div class="table table-hover table-bordered">
<table>
  <thead>
    <tr>
      <th>Место</th>
      <th>Пассажир</th>
      <th>Откуда</th>
      <th>Дата бронирования</th>
    </tr>   
  </thead>
  <tbody>
    <tr>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
    </tr>
    <tr>
      <td>3</td>
      <td>3</td>
      <td>3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>
</div>

app/views/rides/new.html.erb
<h1>Rides#new</h1>
<p>Find me in app/views/rides/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


app/views/static_pages/admin.html.erb
<% provide(:title, 'Управление') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/enter.html.erb
<% provide(:title, 'Вход') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/help.erb
<% provide(:title, 'Личный кабинет') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Главная') %>
<div class="center hero-unit">

  <h3>Когда и куда?</h3>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>


<% if signed_in? && current_user.admin? %>
<div class="form-inline">
<%= radio_button_tag(:transport, "gazel", options = {checked: true}, remote: true) %>
<%= label_tag(:transport_gazel, '"Газель"') %>&nbsp;
<%= radio_button_tag(:transport, "mercedes", remote: true) %>
<%= label_tag(:transport_mercedes, 'микроавтобус "Mercedes"') %>&nbsp;
<%= radio_button_tag(:transport, "hyundai", remote: true) %>
<%= label_tag(:transport_hyundai, 'автобус "Hyundai"') %>
</div>
<% end %>


<div id="partial-area"></div>


  <%= link_to "Стать пассажиром!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/new.html.erb
<% provide(:title, 'Регистрация') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/passengers.html.erb
<% provide(:title, 'Пассажиры') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/profile.html.erb
<% provide(:title, 'Личный кабинет') %>
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name, "Имя" %>
<%= f.text_field :name %>

<%= f.label :lastname, "Фамилия" %>
<%= f.text_field :lastname %>

<%= f.label :phone, "Телефон" %>
<%= f.text_field :phone %>

<%= f.label :settlement, "Откуда" %>
<%= f.select :settlement, options_for_select(["с.Баган", "с.Баклуши", "пос.Безногое", "пос.Брянский",
	"с.Волчанка", "пос.Даниловская Ферма", "с.Довольное", "пос.Дружный", "с.Ильинка", "с.Индерь", "пос.Каревский", "с.Комарье", "с.Комендантка", "с.Красная Грива", "с.Кротово", "пос.Новодоволенский", "г.Новосибирск", "с.Плеханово", "с.Покровка", "д.Сарыбалык", "с.Согорное", "пос.Солонцовый", "с.Суздалка", "с.Травное", "с.Утянка", "пос.Хромовский", "с.Шагалка", "с.Ярки"]), :include_blank => "Пожалуйста, выберите..." %>

<%= f.label :password, "Пароль" %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Подтвердите пароль" %>
<%= f.password_field :password_confirmation %>

app/views/users/_person.html.erb
123

app/views/users/_user.html.erb
<li>
    <%= link_to user.lastname, user %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "удалить", user, method: :delete,
                                  data: { confirm: "Уверены?" } %>
  <% end %>
</li>


app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Обновите свой профиль</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Сохранить", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Пассажиры') %>
<h1>Пассажиры</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Регистрация') %>
<h1>Регистрация</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		  <%= render 'fields', f: f %>
	      <%= f.submit "Создать аккаунт", class: "btn btn-large btn-primary" %>
	    <% end %>
		
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @user.name %> <%= @user.lastname %></h1>
			<h5><%= @user.phone %></h5>
			<h5><%= @user.settlement %></h5>
		</section>
	</aside>
</div>